### ISSUE TITLE
add CI tests for the windows / vcpkg configuration

### ISSUE THREAD

**Issue by tanriol** [tanriol/libftdi1-sys#7]
This may be a good idea just for completeness :-)

@roqvist / @cr1901 if you're interested, feel free to try.

**Comment by cr1901** [comment]
This is prob a @roqvist task; I've no experience using AppVeyor- I cross-compile via Travis if I need Windows builds :P! Last I checked, Travis' support for Windows was iffy.

But yes, this is a good idea.
